name: CVE Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'
jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      scan_name: "CVE"
      tags: "cve"
      severity: "high,critical"
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
